/** Sectors catalogue (from v1). To add a sector: append it to ALL_SECTORS. */
export const ALL_SECTORS: readonly string[] = [
  'Aérospatial',
  'AgriFood',
  'Alimentation saine',
  'AR/VR',
  'B2B',
  'B2C',
  'BeautyTech',
  'Bien-être & Spa',
  'BioTech',
  'Blockchain',
  'Coaching & Performance',
  'Co-living',
  'Communauté & Réseau social',
  'Compliance',
  'Cosmétiques & Skincare',
  'Covoiturage',
  'Creator Economy',
  'Crypto',
  'D2C',
  'Data',
  'DeepTech',
  'DeFi',
  'E-commerce',
  'E-learning',
  'EdTech',
  'Économie circulaire',
  'Énergies renouvelables',
  'ESS',
  'Esport',
  'FashionTech',
  'FinTech',
  'FoodTech',
  'FoodWaste',
  'Formation en ligne',
  'Freelance & Indépendants',
  'FutureOfWork',
  'GreenTech',
  'Hardware & IoT',
  'HealthTech',
  'Hôtellerie',
  'HRTech',
  'IA Générative',
  'Impact social',
  'Impression 3D',
  'Influence marketing',
  'Insertion professionnelle',
  'Intelligence Artificielle',
  'Jeux vidéo',
  'LegalTech',
  'Live shopping',
  'Livraison de repas',
  'Luxe & Haute couture',
  'Machine Learning',
  'Marketplace',
  'Marketplace B2B',
  'MediaTech',
  'MedTech',
  'Métavers',
  'Micro-mobilité',
  'Mobilité durable',
  'Mode durable',
  'Mobility',
  'Néobanque',
  'Newsletter',
  'No-code',
  'Paiement & PayTech',
  'Podcast',
  'Presse en ligne',
  'PropTech',
  'Recommerce & Seconde main',
  'Recrutement & RH',
  'Robotique',
  'SaaS',
  'Santé mentale',
  'Smart City',
  'Smart Home & Domotique',
  'SportTech',
  'Sports extrêmes',
  'Streaming vidéo',
  'Streetwear',
  'Talent management',
  'Télémédecine',
  'Tourisme durable',
  'TravelTech',
  'Tutorat & Soutien scolaire',
  'Véhicule électrique',
  'Web3',
  'WellnessTech',
]
  .slice()
  .sort((a, b) => a.localeCompare(b, 'fr'));

export const POPULAR_SECTORS: readonly string[] = [
  'Creator Economy',
  'E-commerce',
  'EdTech',
  'FinTech',
  'FoodTech',
  'FutureOfWork',
  'GreenTech',
  'HealthTech',
  'IA Générative',
  'PropTech',
  'SaaS',
  'Web3',
];

export const SECTOR_CLUSTERS: Readonly<Record<string, readonly string[]>> = {
  FinTech: ['Néobanque', 'Paiement & PayTech', 'DeFi', 'Crypto', 'B2B'],
  GreenTech: ['Énergies renouvelables', 'Économie circulaire', 'Mobilité durable', 'Impact social'],
  HealthTech: ['MedTech', 'Télémédecine', 'Santé mentale', 'BioTech', 'WellnessTech'],
  EdTech: ['E-learning', 'Formation en ligne', 'Tutorat & Soutien scolaire'],
  'IA Générative': ['Intelligence Artificielle', 'Machine Learning', 'Data', 'SaaS'],
  'E-commerce': ['D2C', 'Marketplace', 'Live shopping', 'Recommerce & Seconde main'],
  'Creator Economy': ['Influence marketing', 'MediaTech', 'Podcast', 'Streaming vidéo'],
};

export const MAX_SECTORS = 5;
