/**
 * Skills catalogue (from v1). To add a skill: append it to ALL_SKILLS (kept sorted at runtime).
 * Users can also type a custom skill; the server trims/dedupes it (see private.clean_tags).
 */
export const ALL_SKILLS: readonly string[] = [
  'Ableton Live',
  'Acting',
  'Adobe XD',
  'After Effects',
  'Agile',
  'Airtable',
  'Animation 2D',
  'Animation 3D',
  'Back-end',
  'Barista',
  'Beatmaking',
  'Blockchain',
  'Blender',
  'Bootstrap',
  'Branding',
  'Bug Bounty',
  'Business Development',
  'Business Plan',
  'Canva',
  'CapCut',
  'Chant',
  'Chorégraphie',
  'CI/CD',
  'Cinema 4D',
  'Coaching de vie',
  'Coaching sportif',
  'Cold email',
  'Color grading',
  'Community Management',
  'Comptabilité',
  'Copywriting',
  'Couture',
  'Création de contenu',
  'CRO',
  'CSS',
  'Cuisine',
  'Cybersécurité',
  'DaVinci Resolve',
  'Danse',
  'Data Analysis',
  'Data Science',
  'Deep Learning',
  'DeFi',
  'Design System',
  'DevOps',
  'Direction artistique',
  'Django',
  'Docker',
  'Drone',
  'DJ',
  'E-commerce',
  'Email Marketing',
  'Excel avancé',
  'Expo',
  'Facebook Ads',
  'FastAPI',
  'Figma',
  'Final Cut Pro',
  'Firebase',
  'Fitness model',
  'FL Studio',
  'Flask',
  'Flutter',
  'Framer',
  'Front-end',
  'Fundraising',
  'Game Design',
  'Gestion de projet',
  'Git',
  'Go',
  'Google Ads',
  'Google Analytics',
  'Google Cloud',
  'GraphQL',
  'Ghostwriting',
  'Growth Hacking',
  'Guitare',
  'HTML',
  'Hubspot',
  'Hardware',
  'Illustration numérique',
  'InDesign',
  'Influence Marketing',
  'Instagram',
  'IoT',
  'JavaScript',
  'Journalisme',
  'Judo',
  'Kotlin',
  'Kubernetes',
  'LangChain',
  'Laravel',
  'Leadership',
  'Lightroom',
  'LinkedIn',
  'LinkedIn Ads',
  'Live streaming',
  'Logic Pro',
  'Logo design',
  'Machine Learning',
  'Make',
  'Management',
  'Mannequin',
  'Mannequin e-commerce',
  'Mannequin mode',
  'Mannequin photo',
  'Marketing',
  'Mastering',
  'Massage',
  'Maya',
  'Méditation',
  'Mixage audio',
  'Mixologie',
  'Mixpanel',
  'MongoDB',
  'Montage vidéo',
  'Motion Design',
  'MySQL',
  'n8n',
  'Nail art',
  'NestJS',
  'Newsletter',
  'Next.js',
  'NFT',
  'NLP',
  'Node.js',
  'Notion',
  'Nutrition',
  'OpenAI API',
  'OSINT',
  'Packaging',
  'Pandas',
  'Pentest',
  'Personal shopper',
  'Personal training',
  'PHP',
  'Photographie',
  'Photographie mariage',
  'Photographie mode',
  'Photographie portrait',
  'Photographie produit',
  'Photoshop',
  'Piano',
  'Pilates',
  'Pixel Art',
  'PNL',
  'Podcast production',
  'PostgreSQL',
  'Power BI',
  'Premiere Pro',
  'Procreate',
  'Product Management',
  'Product Owner',
  'Pro Tools',
  'Prompt Engineering',
  'Prospection B2B',
  'PWA',
  'PyTorch',
  'Python',
  'QA Testing',
  'Rap',
  'React',
  'React Native',
  'Recrutement',
  'Rédaction SEO',
  'Rédaction web',
  'Redis',
  'REST API',
  'Retool',
  'Retouche photo',
  'RGPD',
  'Ruby on Rails',
  'Running',
  'Rust',
  'Salesforce',
  'Sales',
  'Sass',
  'Scrum',
  'SEA',
  'SEO',
  'Service client',
  'SFX makeup',
  'Shopify',
  'Smart Contracts',
  'Social Media Management',
  'Solidity',
  'Sound design',
  'Sophrologie',
  'Spring Boot',
  'SQL',
  'Stable Diffusion',
  'Stand-up',
  'Storyboard',
  'Storytelling',
  'Studio photo',
  'Supabase',
  'Surf',
  'Swift',
  'SwiftUI',
  'Tableau',
  'Tailwind CSS',
  'Tatouage',
  'TensorFlow',
  'Théâtre',
  'TikTok',
  'TikTok Ads',
  'TikTok production',
  'Trading crypto',
  'Traduction FR/EN',
  'Traduction FR/ES',
  'TypeScript',
  'Twitch',
  'UI Design',
  'Unity',
  'Unreal Engine',
  'UX Design',
  'UX Research',
  'UX Writing',
  'Vercel',
  'VFX',
  'Vidéographie',
  'Violon',
  'Vue.js',
  'VR',
  'Web3',
  'Webflow',
  'WordPress',
  'Yoga',
  'YouTube',
  'YouTube production',
  'ZBrush',
  'Zapier',
]
  .slice()
  .sort((a, b) => a.localeCompare(b, 'fr'));

export const POPULAR_SKILLS: readonly string[] = [
  'Figma',
  'React Native',
  'Copywriting',
  'SEO',
  'Motion Design',
  'Photographie',
  'TikTok',
  'YouTube production',
  'Business Development',
  'Data Analysis',
  'Beatmaking',
  'Coaching sportif',
];

/** "Dans le même style" suggestions (from v1). */
export const SKILL_CLUSTERS: Readonly<Record<string, readonly string[]>> = {
  React: ['React Native', 'Next.js', 'TypeScript', 'JavaScript', 'Vue.js', 'Tailwind CSS'],
  'React Native': ['React', 'Expo', 'TypeScript', 'Flutter', 'Swift', 'Kotlin'],
  Figma: ['UI Design', 'UX Design', 'Design System', 'Framer', 'Adobe XD'],
  TikTok: ['Instagram', 'YouTube', 'CapCut', 'Création de contenu', 'Community Management'],
  Photographie: [
    'Lightroom',
    'Photoshop',
    'Studio photo',
    'Retouche photo',
    'Drone',
    'Vidéographie',
  ],
  Beatmaking: ['Ableton Live', 'FL Studio', 'Mixage audio', 'Mastering', 'Sound design'],
  SEO: ['SEA', 'Google Ads', 'Copywriting', 'Rédaction web', 'Google Analytics'],
  'Machine Learning': ['Deep Learning', 'Python', 'TensorFlow', 'PyTorch', 'Data Science', 'NLP'],
  'Node.js': ['Back-end', 'PostgreSQL', 'REST API', 'GraphQL', 'Supabase'],
  'Motion Design': ['After Effects', 'Animation 2D', 'Animation 3D', 'Cinema 4D', 'Blender', 'VFX'],
  Copywriting: ['Rédaction web', 'Rédaction SEO', 'Newsletter', 'Storytelling', 'UX Writing'],
  Python: ['Machine Learning', 'Data Science', 'FastAPI', 'Django', 'Pandas'],
  Marketing: ['Growth Hacking', 'Email Marketing', 'SEO', 'Facebook Ads', 'Branding'],
  Sales: ['Business Development', 'Prospection B2B', 'Cold email', 'Hubspot', 'Salesforce'],
};

export const MAX_SKILLS = 10;
